name: Restonomer CI

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging", "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Clean SBT Cache
        run: |
          rm -rf $HOME/.ivy2/cache
          rm -rf $HOME/.sbt/boot/
      - name: Scalafmt Check
        run: sbt scalafmtCheckAll
      - name: Scalafix Check
        run: sbt "scalafixAll --check"
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Unit Tests
        run: sbt test
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Integration Tests
        run: sbt IntegrationTest/test
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
