name: Restonomer CI

on:
  push:
    branches: ["staging"]
  pull_request:
    branches: ["staging", "master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Scalafmt Check
        run: sbt scalafmtCheckAll
      - name: Run Fake GCS Server
        uses: addnab/docker-run-action@v3
        with:
          image: fsouza/fake-gcs-server:latest
          options: -p 4443:4443
      - name: Run Unit Tests
        run: sbt test
      - name: Run Integration Tests
        run: sbt IntegrationTest/test
